import Head from "next/head";
import styles from "@/styles/Profile.module.css";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Profile Page</div>
    </>
  );
}
