import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Landing.module.css";
import { supabase } from "@/lib/supabase";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [status, setStatus] = useState("Checking...");

  useEffect(() => {
    async function checkConnection() {
      const { data, error } = await supabase
        .from("user_table")
        .select("*")
        .limit(1);
      if (error) {
        console.error("Connection error:", error);
        setStatus(`❌ Error: ${error.message}`);
      } else {
        console.log("Connection successful:", data);
        setStatus("✅ Connected to Supabase!");
      }
    }

    checkConnection();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        Landing Page
        <div>
          <h1>{status}</h1>
        </div>
      </div>
    </>
  );
}
