import Head from "next/head";
import Footer from "@/components/footer";

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Dashboard Page</div>
      <Footer />
    </>
  );
}
